FROM ubuntu

RUN apt-get update && \
    apt-get install -y npm && \
    npm cache clean --force

RUN mkdir /app
ADD . /app
WORKDIR /app

RUN npm install express body-parser && \
    npm install cors && \
    npm install mysql2

EXPOSE 5000
CMD ["node", "server.js"]
