apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: adaliv/k8s_node:1.2
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: rootpassword
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort
